-- criar o arquivo banco de dados
CREATE DATABASE [dbExe03_BD1_050925];

--Utilizar o banco de dados 
USE [dbExe03_BD1_050925];

--Criar uma tabela de cargos 
CREATE TABLE TB_CARGO (
ID_CARGO INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
DESCRICAO_CARGO VARCHAR (50) NOT NULL UNIQUE,
SALARIO_CARGO NUMERIC (7,2) NOT NULL );

--Seleciona tabela criada
SELECT * FROM TB_CARGO;

--Inserir dados na tabela cargo
INSERT INTO TB_CARGO (DESCRICAO_CARGO, SALARIO_CARGO) VALUES
('Diretor', 25000.00), 
('Gerente de RH', 14000.00), 
('Gerente de TI', 13750.00), 
('Auxiliar Produção', 3800.00), 
('Técnico', 2500.00);

--Criar tabela ESCOLARIDADE
CREATE TABLE TB_ESCOLARIDADE (
ID_ESCOLARIDADE INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
DESCRICAO_ESCOLARIDADE VARCHAR (60) NOT NULL UNIQUE);

--Selecionar a tabela escolaridade 
SELECT * FROM TB_ESCOLARIDADE;

--Inserir dados na tabela escolaridade
INSERT INTO TB_ESCOLARIDADE (DESCRICAO_ESCOLARIDADE) VALUES 
('Fundamental'), 
('Profissionalizante'), 
('Ensino Médio'), 
('Técnico'), 
('Superior'), 
('Especializado'), 
('Mestrado'), 
('Doutor PHD');

CREATE TABLE TB_SETOR (
ID_SETOR INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
DESCRICAO_SETOR VARCHAR (40) NOT NULL UNIQUE,
RESPONSAVEL_SETOR VARCHAR (40) NOT NULL);
--cria tabela escolaridade


SELECT * FROM TB_SETOR;
--seleciona na tabela setor

INSERT INTO TB_SETOR ( DESCRICAO_SETOR, RESPONSAVEL_SETOR) values
('Diretoria','Nelsinho'),
('RH', 'Denise'),
('Produção', 'Ana'),
('Area TI', 'Rosa');
--insere dados na tabela escolaridade

--Criar tabela de estado civi
CREATE TABLE TB_ESTADO_CIVIL (
ID_ESTADO_CIVIL INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
DESCRICAO_ESTADO_CIVIL VARCHAR (40) NOT NULL UNIQUE);

--Selecionar os dados da tabela estado civil
SELECT * FROM TB_ESTADO_CIVIL;

--Inserir dados na tabela Estado civil
INSERT INTO TB_ESTADO_CIVIL (DESCRICAO_ESTADO_CIVIL) VALUES
('Solteiro'),
('Casado'),
('Viuvo'),
('Divorciado'),
('União Estável');

CREATE TABLE TB_DEFICIENCIA (
ID_DEFICIENCIA INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
DESCRICAO_DEFICIENCIA VARCHAR (40) NOT NULL UNIQUE);
--cria tabela deficiencia 

SELECT * FROM TB_DEFICIENCIA;
--seleciona tabela deficiencia

insert into TB_DEFICIENCIA (DESCRICAO_DEFICIENCIA) VALUES 
('Não possui'),
('Auditiva'),
('visual'),
('Cognitiva ou Neurológica'),
('Motora');

--Criar tabela de generos
CREATE TABLE TB_GENERO (
ID_GENERO INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
DESCRICAO_GENERO VARCHAR (40) NOT NULL UNIQUE);

--Selecionar a tabela de generos
SELECT * FROM TB_GENERO;

--Inserir dados nessa tabela
INSERT INTO TB_GENERO (DESCRICAO_GENERO) VALUES
('Masculino'),
('Feminino'),
('Transgênero'),
('neutro'),
('Não-binário'),
('Agênero'),
('Pangênero');

--Criar tabela principal Funcionarios
CREATE TABLE TB_FUNCIONARIO (
MATRICULA_FUNCIONARIO INT NOT NULL PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR (60) NOT NULL,
ENAIL_FUNCIONARIO VARCHAR (100) NOT NULL UNIQUE,
ID_CARGO INT NOT NULL,
DTA_ADM_FUNCIONARIO DATE NOT NULL,
DTA_NASC_FUNCIONARIO DATE NOT NULL,
ID_ESCOLARIDADE INT NOT NULL,
RG_FUNCIONARIO CHAR (12) NOT NULL UNIQUE,
CPF_FUNCIONARIO CHAR (14) NOT NULL UNIQUE,
ENDERECO_FUNCIONARIO VARCHAR (120) NOT NULL,
ID_ESTADO_CIVIL INT NOT NULL,
FONE_RES_FUNCIONARIO CHAR (14) NOT NULL,
FONE_CEL_FUNCIONARIO CHAR (16) NOT NULL UNIQUE,
DEPENDENTE_FUNCIONARIO INT NOT NULL,
SEXO_FUNCIONARIO CHAR (1) NOT NULL,
ID_GENERO INT NOT NULL,
ID_SETOR INT NOT NULL,
ID_DEFICIENCIA INT NOT NULL,
STATUS_FUNCIONARIO VARCHAR (40) NOT NULL,
DADOS_MEDICO_FUNCIONARIO TEXT NOT NULL,
NOME_SOCIAL_FUNCIONARIO VARCHAR (60) NOT NULL

--Chaves estrangeiras
FOREIGN KEY (ID_CARGO) REFERENCES TB_CARGO (ID_CARGO),
FOREIGN KEY (ID_ESCOLARIDADE) REFERENCES TB_ESCOLARIDADE (ID_ESCOLARIDADE),
FOREIGN KEY (ID_SETOR) REFERENCES TB_SETOR (ID_SETOR),
FOREIGN KEY (ID_ESTADO_CIVIL) REFERENCES TB_ESTADO_CIVIL (ID_ESTADO_CIVIL),
FOREIGN KEY (ID_DEFICIENCIA) REFERENCES TB_DEFICIENCIA (ID_DEFICIENCIA),
FOREIGN KEY (ID_GENERO) REFERENCES TB_GENERO (ID_GENERO),
);