--/* Cria arquivo de banco de dados */
CREATE DATABASE [dbExe02_bd1_220825];

--/* Acessa o banco de dados -> USE  */
USE [dbExe02_bd1_220825];

--/* Criar tabela de dados */
CREATE TABLE TB_ESCOLA (
	COD_ESCOLA INT NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR (60) NOT NULL UNIQUE,
	CIDADE_ESCOLA VARCHAR (60) NOT NULL);

/* Inserindo dados na tabela*/
INSERT INTO TB_ESCOLA(COD_ESCOLA, DESCRICAO, CIDADE_ESCOLA) VALUES
	(10, 'Etec Lauro gomes', 'São Bernado do campo'),
	(11, 'Etec Jorge Street', 'São Caetano do Sul'),
	(17, 'Etec Julio de Mesquita', 'Santo André'),
	(166, 'Etec JK', 'Diadema');

/* Exibe a tabela escola */
SELECT * FROM TB_ESCOLA;

/* Criar tabela do curso */
CREATE TABLE TB_CURSO (
	ID_CURSO INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	CODIGO_ESCOLA INT NOT NULL,
	DESCRICAO_CURSO VARCHAR (60) NOT NULL,
	DURACAO_CURSO VARCHAR (40) NOT NULL,
	CATEGORIA_CURSO VARCHAR (30) NOT NULL,
	ANO_CURSO VARCHAR (4) NOT NULL,
	SEMESTRE_CURSO VARCHAR (2) NOT NULL,
	PERIODO_CURSO VARCHAR (30) NOT NULL,
	FOREIGN KEY (CODIGO_ESCOLA) REFERENCES TB_ESCOLA (COD_ESCOLA));

/* Exibir tabela curso */
SELECT * FROM TB_CURSO;

/* Inserir dados na tabela curso */
INSERT INTO TB_CURSO (CODIGO_ESCOLA, DESCRICAO_CURSO, DURACAO_CURSO, CATEGORIA_CURSO, ANO_CURSO, SEMESTRE_CURSO, PERIODO_CURSO
) VALUES 
	(10, 'Tecnico em Desenvolvimento de sistemas', '3s', 'Modular', '2025', '2s', 'Vespertino'),
	(11, 'Tecnico Juridico', '3s', 'Modular', '2025', '2s', 'Noturno'),
	(17, 'Tecnico em Nutrição', '3s', 'Modular', '2025', '2s', 'Matutino'),
	(166, 'Tecnico em Desenvolvimento de Sistemas', '3s', 'Modular', '2025', '2s', 'Vespertino');

/* Criar Tabela candidato */
CREATE TABLE TB_CANDIDATO (
	ID_CANDIDATO INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	ID_CURSO INT NOT NULL,
	NOME_CANDIDATO VARCHAR (60) NOT NULL,
	RG_CANDIDATO VARCHAR (12) NOT NULL UNIQUE,
	CPF_CANDIDATO VARCHAR (14) NOT NULL UNIQUE,
	EMAIL_CANDIDATO VARCHAR (80) NOT NULL UNIQUE,
	FONE_CANDIDATO VARCHAR (16) NOT NULL UNIQUE,
	ENDERECO_CANDIDATO VARCHAR (255) NOT NULL,
	CEP_CANDIDATO VARCHAR (9) NOT NULL,
	DATA_NASCIMENTO_CANDIDATO DATE NOT NULL,
	DATA_INSCRICAO_CANDIDATO DATE NOT NULL,
	ESCOLARIDADE_CANDIDATO VARCHAR (60) NOT NULL,
	STATUS_CANDIDATO VARCHAR (40) NOT NULL,
	RESPONSAVEL_CANDIDATO VARCHAR (60),
	SENHA_CANDIDATO VARCHAR (8) NOT NULL
	FOREIGN KEY (ID_CURSO) REFERENCES TB_CURSO (ID_CURSO));

/* Exibir a tabela de candidatos */
SELECT * FROM TB_CANDIDATO;

/* Adicionar candidato */
INSERT INTO TB_CANDIDATO (ID_CURSO, NOME_CANDIDATO, RG_CANDIDATO, CPF_CANDIDATO, EMAIL_CANDIDATO, FONE_CANDIDATO, 
ENDERECO_CANDIDATO, CEP_CANDIDATO, DATA_NASCIMENTO_CANDIDATO, DATA_INSCRICAO_CANDIDATO, ESCOLARIDADE_CANDIDATO, 
STATUS_CANDIDATO, RESPONSAVEL_CANDIDATO, SENHA_CANDIDATO) VALUES
	(10, 'Valter Sérgio Ribeiro Tertuliano', '47505270-5', '07845179914', 'valtertert@gmail.com', '16994030287', 
	'Rua Francisco Masini 254, Jd Irene, Santo André - SP', '09170-600', '13/10/1994', GETDATE(), 'Ensino Médio Completo', 
	'Aprovado', 'Vaniâ Tertuliano', '12345678');

